### ISSUE TITLE
View results: Error in deleting files 

### ISSUE THREAD

**Issue by sapofra** [JRCSTU/co2wui#78]
If I try to delete the runs I get an error: 
![image](https://user-images.githubusercontent.com/29604134/61049523-fc2a1c80-a3e4-11e9-979e-eb8f6d167619.png)

**Comment by dimitriskomnos** [comment]
FYI, the file(s) are do get deleted later

**Comment by stefanocorsi** [comment]
I don't know... partially the problem could be related to the mixed/multiuser access to the server... I'll do some testing.

**Comment by dimitriskomnos** [comment]
I see the same testing in my pc the packages @ankostis is builting. 

This time the error I get is: 
```console
2019-07-15 16:46:41,661:ERROR:flask.app:Exception on /run/delete-results [POST]
Traceback (most recent call last):
  File "C:\Apps\conda3.7\envs\co2\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Apps\conda3.7\envs\co2\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Apps\conda3.7\envs\co2\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Apps\conda3.7\envs\co2\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Apps\conda3.7\envs\co2\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Apps\conda3.7\envs\co2\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Apps\conda3.7\envs\co2\lib\site-packages\co2wui\app.py", line 477, in delete_results
    shutil.rmtree(osp.join("output", runid))
  File "C:\Apps\conda3.7\envs\co2\lib\shutil.py", line 513, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Apps\conda3.7\envs\co2\lib\shutil.py", line 397, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Apps\conda3.7\envs\co2\lib\shutil.py", line 395, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'output\\6868\\logfile.txt'
```
and the files are not getting deleted.

**Comment by stefanocorsi** [comment]
This error could be related to using the app in a multi-user environment (web server). I'll close the issue and we'll see if in the new version (packaged one) it will represent itself.
