### ISSUE TITLE
Simulation plan file does not run 

### ISSUE THREAD

**Issue by dimitriskomnos** [JRCSTU/co2wui#80]
I tried to run a simulation plan in both server and in my loacal VM, 
but it fails to both (in console using co2mpas it is fine). The base case is running, but not the rest. 
Here the error I got in the server: 

```
Done! [94.42 sec]
FileNotFoundError
    raise FileNotFoundError
  File "c:\users\administrator\co2mpas\co2mpas\co2mpas\__init__.py", line 232, in _yield_files
    solutions, it = {}, list(_yield_files(*input_files))
  File "c:\users\administrator\co2mpas\co2mpas\co2mpas\__init__.py", line 283, in run_core
    bases.update(run_core(core_model, cmd_flags, timestamp, fp))
  File "c:\users\administrator\co2mpas\co2mpas\co2mpas\__init__.py", line 371, in run_plan
    r['res'] = e.process(fn, *args, **kw) if e else fn(*args, **kw)
  File "c:\ProgramData\Miniconda3\lib\site-packages\schedula\utils\asy.py", line 124, in _process_funcs
    name, funcs, executor, *args, **kw
  File "c:\ProgramData\Miniconda3\lib\site-packages\schedula\utils\asy.py", line 167, in async_process
    sol=self, callback=_callback, sol_name=self.full_name + (node_id,)
  File "c:\ProgramData\Miniconda3\lib\site-packages\schedula\utils\sol.py", line 594, in _evaluate_function
    **kw)
  File "c:\ProgramData\Miniconda3\lib\site-packages\schedula\utils\sol.py", line 620, in _evaluate_node
Traceback (most recent call last):
  FileNotFoundError()
Failed DISPATCHING 'run_plan' due to:
CO2MPAS output written into (output\5268\20190711_134948-co2mpas_simplan.xlsx).
```

**Comment by stefanocorsi** [comment]
It doesn't run with co2mpas command line. 
However the co2wui runs with co2mpas 4 commit c33aceb2 (it may be solved in later commits).

**Comment by stefanocorsi** [comment]
@dimitriskomnos will report this to the Co2mpas repo
