### ISSUE TITLE
Error in uploading files for simulating and synchronizing

### ISSUE THREAD

**Issue by dimitriskomnos** [JRCSTU/co2wui#86]
With Kostis help, I am doing some tests in the packages he creates. 
In the co2wui I get the errors below when I try to upload a file.

Running a simulation: 
```console
[2019-07-15 16:26:21,202] ERROR in app: Exception on /run/add-file [POST]
Traceback (most recent call last):
  File "C:\Apps\conda3.7\envs\co2\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Apps\conda3.7\envs\co2\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Apps\conda3.7\envs\co2\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Apps\conda3.7\envs\co2\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Apps\conda3.7\envs\co2\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Apps\conda3.7\envs\co2\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Apps\conda3.7\envs\co2\lib\site-packages\co2wui\app.py", line 398, in add_file
    f.save(osp.join("input", secure_filename(f.filename)))
  File "C:\Apps\conda3.7\envs\co2\lib\site-packages\werkzeug\datastructures.py", line 2799, in save
    dst = open(dst, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'input\\co2mpas_demo-1.xlsx'
```

Synchronizing: 
```console
[2019-07-15 16:28:14,653] ERROR in app: Exception on /sync/add-sync-file [POST]
Traceback (most recent call last):
  File "C:\Apps\conda3.7\envs\co2\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Apps\conda3.7\envs\co2\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Apps\conda3.7\envs\co2\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Apps\conda3.7\envs\co2\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Apps\conda3.7\envs\co2\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Apps\conda3.7\envs\co2\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Apps\conda3.7\envs\co2\lib\site-packages\co2wui\app.py", line 622, in add_sync_file
    f.save(osp.join("sync/input", secure_filename(f.filename)))
  File "C:\Apps\conda3.7\envs\co2\lib\site-packages\werkzeug\datastructures.py", line 2799, in save
    dst = open(dst, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'sync/input\\20190715_091453-summary.xlsx'
```

**Comment by dimitriskomnos** [comment]
As @ankostis [referred to his comment](https://github.com/JRCSTU/co2wui/issues/87#issuecomment-511508852) in the issue #87, 
the problem is that it searches in the directory that co2wui runs for the paths: 
- input
- output
- sync/input
- sync/output

that exist in the git repo. 
Since they are not there it throws an error. 
With Kostis, we created these paths and it run. 
The rest in the #87

**Comment by dimitriskomnos** [comment]
## Please note

The folders:
- /input and ./output for the simulation files;
- ./syn/input and ./syn/output

are created automatically and only if co2wui is open by the console!
